### ISSUE TITLE
Issue with ng-social-links

### ISSUE THREAD

**Issue by rakuemoevi** [aramwram/ng-social-links#1]
Hi, 
I just ran into an issue and don't know how to solve it. I have follow instruction given in demo section. I've clone the repo with link:
**https://codeload.github.com/aramwram/ng-social-links/zip/master**, then run ng start and i get this error
src/app/app.component.ts:21:38 - error TS2307: Cannot find module 'ng-social-links' or its corresponding type declarations.
When trying to install with `ng i --save ng-social-links` i get the following error: **_code ENOSELF
npm ERR! Refusing to install package with name "ng-social-links" under a package
npm ERR! also called "ng-social-links". Did you name your project the same
npm ERR! as the dependency you're installing?_**
I don't know what to do now. Can you enligth me?

**Comment by aramwram** [comment]
Hello, @rakuemoevi .

I didn't get why you've been trying to install `ng-social-links` from within the `ng-social-links` repository and not under your own project?

Please, describe your goal. Do you want to contribute?

**Comment by rakuemoevi** [comment]
Hi thanks for replying,
In fact i have install ng-social-links into my own project before, but unfortunately whatspp share doesn't work so i guessed that it must have an exemple into ng-social-links repository itself it was the goal for which i attempt to instal it like that into the repository itself but it doesn't work.
So my issue is the working of whatsapp share.So if you can help me with some snippet it will be really great!!!Thanks!!!

**Comment by aramwram** [comment]
Hi @rakuemoevi . Sorry for such a long delay. Please, find examples in ng-social-link demo app. Also, you can check how twitter works in other projects, e.g. here https://github.com/kesteckb/COMSM-SEGP/blob/c6880f4713f45a965e938c600089b98173565ee0/SugarRushSite/src/app/share-modal/share-modal.component.ts.
